spring:
  application:
    name: wind-ai-code-back
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yefeng_ai_code
    username: root
    password: 031214t+
server:
  port: 2411
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.yefeng.yefengaicode.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
