spring:
  application:
    name: wind-ai-code-back
server:
  port: 2411
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.yefeng.yefengaicode.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
