spring:
  application:
    name: wind-ai-code-back
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yefeng_ai_code
    username: root
    password: 031214t+
  profiles:
    active: local
server:
  port: 2411
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.yefeng.yefengaicode.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: API_KEY
      model-name: deepseek-chat
      strict-json-schema: true
      response-format: json_object
      max-tokens: 8192
      log-requests: true
      log-responses: true
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: API_KEY
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true

mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.yefeng.yefengaicode.mapper: debug